apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
spec:
  selector:
    turboEnigma: {{ .Release.Name }}
{{- if $.Values.ingress.enabled }}
  type: ClusterIP
{{- else }}
  type: NodePort
{{- end }}
  ports:
    - protocol: TCP
      name: http
      port: 80
      targetPort: http
    {{- if not $.Values.ingress.enabled }}
      nodePort: {{ $.Values.service.nodePort }}
    {{- end }}
