name: Run CI

on: [push, pull_request]

jobs:
  build:
    name: CI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: '^1.16'

      - name: Go Version
        run: go version

      - name: Go Mod tidy
        run: go mod tidy
      
      - name: Run Revive Action by pulling pre-built image
        uses: docker://morphy/revive-action:v2
        with:
          config: revive.toml

      - name: Go tests
        run: go test -race -v ./... -coverprofile=coverage.out -covermode=atomic

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.out
          fail_ci_if_error: true
